# Configuration file for Netlify Serverless Backend Functions

[build]
  functions = "netlify/functions"

# Proxy / Redirect URL agar lebih bersih (opsional)
[[redirects]]
  from = "/api/hello"
  to = "/.netlify/functions/hello"
  status = 200

[[redirects]]
  from = "/api/quotes"
  to = "/.netlify/functions/quotes"
  status = 200
